x=10
y=12
z=x+y
z
p=x>y
is.integer(x)
as.integer(y)
q=TRUE 
p&q
p|q
class(p)
class(x)
as.integer(3.14)
as.integer(yaash)
as.character(fybsc cs 3198546454554)
as.character(JOR)
as.array(12,16,18)
as.data.frame.matrix(1010101010)
as.data.frame.matrix(x,y)
!p
!x
!y
w=-10
!w
!w&x
s=5.5
class(s)
as.formula((x+y)|z)
is.language(p)
is.language(w)
sqrt(144)
c(7,8,9,95)
length(c(7,8,9,95))
c("yy","zz","ss")
a=c("yy","zz","ss")
b=c(7,8,9,95)
c(a,b)
m=10
M=50
sqrt(M)
n=(c(1,2,3,4,5,6))
m=(c(4,5,6))
m+n
m/n
m*n
m-n
t=matrix(c(2,4,8,16,32,64),nrow=2,ncol=3,byrow=TRUE)
t[2,3]
head(faithful)
help("faithful")
dim(faithful)         
faithful         
duration=faithful$eruptions         
range(duration)
breaks=seq(1.5,5.5,by=0.5)
breaks
duration.cut= cut (duration, breaks, right = FALSE)
duration.cut
duration.freq=table(duration.cut)
duration.freq
help(cut)
cbind(duration.freq)
duration=faithful$waiting
range(duration)
breaks=seq(43,96,by=4)
breaks
duration.cut=cut(duration,breaks,right = FALSE)
duration.cut
duration.freq=table(duration.cut)
duration.freq
cbind(duration.freq)
help("hist")
hist(duration,right=FALSE)
help("cbind")
colors=c("red","yellow","magenta","orange","blue","pink","cyan","black","grey","brown","purple","sky blue")
hist(duration,right=FALSE,col=colors,main="Old Faithful Eruptions",xlab="Duration minutes")
library(MASS)
painters
head(painters)
help("painters")
painters$School
school=painters$School
school.freq=table(school)
school.freq
